This is my own setting of Emacs.

* Usage
Put the whole directory to =~/.emacs.d=

* External packages
Install those optional third-party packages to setup for certain languages.

** C/C++
*Clangd* is used for C and C++ support.

** CMake
#+begin_src shell
pip install cmake-language-server
#+end_src

** Python
Python language server
[[https://github.com/palantir/python-language-server][plys]] needs to be installed:

#+begin_src shell
pip install 'python-language-server[all]'
#+end_src

** Bash
#+begin_src shell
[sudo] npm install -g bash-language-server
#+end_src

** HTML & CSS
Install [[https://github.com/vscode-langservers/vscode-html-languageserver][HTML language Server]] and [[https://github.com/vscode-langservers/vscode-css-languageserver-bin][CSS language server]] by
#+begin_src shell
[sudo] npm install -g vscode-html-languageserver-bin
[sudo] npm install -g vscode-css-languageserver-bin
#+end_src
** Elm
#+begin_src shell
[sudo] npm i -g @elm-tooling/elm-language-server
#+end_src
** Javascript & Typescript
*** Linter and formatters
#+begin_src shell
[sudo] npm i -g eslint
[sudo] npm i -g prettier
#+end_src

*** lsp mode support
#+begin_src shell
[sudo] npm i -g typescript-language-server
[sudo] npm i -g typescript
#+end_src

** Json
#+begin_src shell
[sudo] npm i -g vscode-json-languageserver
#+end_src

** Markdown lint
#+begin_src shell
[sudo] npm install -g markdownlint-cli
#+end_src

** Latex
   Install [[https://github.com/astoff/digestif][digestif]]
** OCaml/Reaspn
Follow the instruction on https://ocaml.org/docs/install.html#OPAM to setup OPAM and OCamlc. And install the following packages:

#+begin_src sh
opam install utop # Better repl
opam install ocamlformat # Formatter
opam install merlin # IDE features
opam install ocp-indent
opam install reason # Reason ML
#+end_src

*** On Windows
Install opam on WSL and use [[https://github.com/leongrdic/wsl-alias][wsl-alias]]. Add =eval $(opam env)= to =~/.wsl-alias/env.sh=.

#+begin_src sh
b wsl-alias add opam opam
b wsl-alias add ocamlformat ocamlformat
b wsl-alias add ocaml ocaml
b wsl-alias add ocamlc ocamlc
b wsl-alias add utop utop
b wsl-alias add ocamlmerlin ocamlmerlin
b wsl-alias add dune dune
b wsl-alias add ocp-indent ocp-indent
b wsl-alias add ocamlfind ocamlfind
b wsl-alias add refmt refmt
#+end_src

** Rust
Some tools that needed for ~rust-mode~, ~lsp-rust~, and ~cargo-mode~.

#+begin_src text
rustup component add rls rust-analysis rust-src
cargo install rustfmt
cargo install cargo-check
rustup component add clippy-preview
#+end_src

** Yaml
Install [[https://github.com/adrienverge/yamllint][yamllint]]
~pip install yamllint~

Install [[https://github.com/redhat-developer/yaml-language-server][yaml-language-server]]
npm install -g yaml-language-server
